name: Trivy FS Scan

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trivy fs scan (report)
      uses: aquasecurity/trivy-action@0.20.0
      continue-on-error: true
      with:
        scan-type: fs
        scanners: vuln,secret,misconfig
        ignore-unfixed: true
        severity: HIGH,CRITICAL
        format: sarif
        output: trivy-fs.sarif
        exit-code: "0"

    - name: Upload SARIF to GitHub Security Center
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-fs.sarif

    - name: Count HIGH/CRITICAL from SARIF
      id: findings
      run: |
        count=$(jq '[.. | .severity? | select(.=="HIGH" or .=="CRITICAL")] | length' trivy-fs.sarif)
        echo "count=$count" >> $GITHUB_OUTPUT
        echo "Nombre de vulnérabilités HIGH+CRITICAL: $count"

    - name: Fail if vulns found (Quality Gate)
      if: steps.findings.outputs.count != '0'
      run: |
        echo "❌ Des vulnérabilités critiques ou high ont été détectées !";
        exit 1

    - name: Report success message
      if: steps.findings.outputs.count == '0'
      run: |
        echo "✅ Aucun problème HIGH/CRITICAL. Excellent travail !"
